name: Build wheel and attach to GitHub Release
on:
  release:
    types: [published]
jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"
    - name: Install build
      run: python3 -m pip install build --user
    - name: Build wheel and sdist
      run: python3 -m build
    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: dist/*
